<script>
	// The settings drawer.
	//
	// Full height down the left edge, and deliberately **not** modal: no
	// backdrop, the page behind stays scrollable and clickable. Live
	// preview is the whole point - you drag a slider and watch the
	// headings resize - so anything that blocks the page would defeat it.
	//
	// Every control is derived from data rather than hardcoded: the site
	// fields from `siteFields` below, the typography controls from the
	// font catalogue, so a family only ever offers axes it actually has.
	import {
		families,
		findFamily,
		axisKeys,
		rampValues,
		fixedValue,
		RAMP,
		CHOICE,
		FLAG
	} from '../../markdown/fonts.js';
	import { fallbackColors } from '../../markdown/brandColors.js';
	import { readSettings, joinFrontmatter, themeObject, writeSettings } from './settings-file.js';

	let { onclose } = $props();

	let loading = $state(true);
	let error = $state(null);
	let saving = $state(false);

	// The whole file, so a save rewrites only what changed and leaves
	// every other key - and the body - alone.
	let file = $state({ data: {}, body: '' });

	// Held apart from `data` until a theme field is actually edited, so a
	// site that wrote `theme: default` keeps that spelling unless it has a
	// reason not to. Editing only the title must not silently rewrite the
	// theme into its object form.
	let editedTheme = $state(null);

	const theme = $derived(editedTheme ?? themeObject(file.data.theme));
	const family = $derived(findFamily(theme.font));
	const colors = $derived([0, 1].map((index) => theme.colors?.[index] ?? fallbackColors[index]));

	// Top-level frontmatter keys, in the order they read as a form. Only
	// settings vowel actually consumes are here - `author` is in both demo
	// settings.md files and is read by nothing, so it isn't offered.
	const siteFields = [
		{ key: 'title', label: 'Title', hint: 'The site name, shown in the header' },
		{ key: 'tagline', label: 'Tagline', hint: 'Shown as the homepage hero' },
		{ key: 'breadcrumb', label: 'Breadcrumb', hint: 'Label for the site root in navigation' },
		{ key: 'domain', label: 'Domain', hint: 'Needed for the sitemap and feed' },
		{ key: 'icon', label: 'Icon', hint: 'An emoji, or a path to an image' },
		{ key: 'logo', label: 'Logo', hint: 'Path to an SVG or image' },
		{ key: 'wordmark', label: 'Wordmark', hint: 'Path to an SVG or image' }
	];

	// Setting a ramp variable on the document is the whole of live
	// preview: --*-delta is a calc() over these, so all six heading levels
	// and the header recompute themselves.
	const preview = $derived.by(() => {
		if (!family) return [];

		return family.axes
			.filter((axis) => axis.kind === RAMP)
			.flatMap((axis) => {
				const { h1, h6, power } = rampValues(axis, theme);
				const value = (amount) =>
					axis.unit === 'x' ? `calc(var(--base-font-size) * ${amount})` : `${amount}${axis.unit}`;

				return [
					[`--${axis.variable}-start`, value(h6)],
					[`--${axis.variable}-end`, value(h1)],
					[`--${axis.variable}-power`, String(power)]
				];
			});
	});

	$effect(() => {
		const root = document.documentElement;
		for (const [name, value] of preview) root.style.setProperty(name, value);
		// The font family, the colour scheme and the non-ramped axes all
		// need a rebuild to see: the other seven fonts aren't served, and
		// the colour ramps are generated by colorhorse on the server.
	});

	$effect(() => {
		readSettings()
			.then((result) => (file = result))
			.catch((e) => (error = e.message))
			.finally(() => (loading = false));
	});

	function setField(key, value) {
		const data = { ...file.data };
		if (value === '') delete data[key];
		else data[key] = value;
		file = { ...file, data };
	}

	function setTheme(key, value) {
		editedTheme = { ...theme, [key]: value };
	}

	/** Both seeds are written together - colorhorse takes a pair. */
	function setColor(index, value) {
		setTheme('colors', colors.map((current, position) => (position === index ? value : current)));
	}

	async function save() {
		saving = true;
		error = null;

		const data = editedTheme ? { ...file.data, theme: editedTheme } : file.data;

		try {
			await writeSettings('settings.md', joinFrontmatter(data, file.body));
			// No reload: the write lands in sourceFolder, the watcher
			// rebuilds and voot's live-reload client patches the page - the
			// same path a hand edit takes.
			onclose();
		} catch (e) {
			error = e.message;
		} finally {
			saving = false;
		}
	}
</script>

<aside class="settings-drawer" aria-label="Site settings">
	<header>
		<h2>Settings</h2>
		<button class="close" onclick={onclose} title="Close settings">&#10005;</button>
	</header>

	{#if loading}
		<p class="note">Reading settings.md…</p>
	{:else}
		<section>
			<h3>Site</h3>
			{#each siteFields as field (field.key)}
				<label class="field">
					<span>{field.label}</span>
					<input
						type="text"
						value={file.data[field.key] ?? ''}
						placeholder={field.hint}
						title={field.hint}
						oninput={(event) => setField(field.key, event.currentTarget.value)}
					/>
				</label>
			{/each}
		</section>

		<section>
			<h3>Colors</h3>
			<p class="note">Two seeds; every shade on the site is generated from them.</p>
			{#each ['One', 'Two'] as label, index (label)}
				<label class="field color">
					<span>{label}</span>
					<input
						type="color"
						value={colors[index]}
						oninput={(event) => setColor(index, event.currentTarget.value)}
					/>
					<input
						type="text"
						class="hex"
						value={colors[index]}
						spellcheck="false"
						oninput={(event) => setColor(index, event.currentTarget.value)}
					/>
				</label>
			{/each}
		</section>

		<section>
			<h3>Typography</h3>
			<label class="field">
				<span>Font</span>
				<select value={theme.font ?? ''} onchange={(event) => setTheme('font', event.currentTarget.value)}>
					<option value="">None</option>
					{#each families as option (option.name)}
						<option value={option.name}>{option.name}</option>
					{/each}
				</select>
			</label>

			{#if !family}
				<p class="note">Pick a font to set a heading scale.</p>
			{:else}
				<p class="note">Sizes and spacing preview as you drag. The font and colors apply on save.</p>

				{#each family.axes as axis (axis.id)}
					{@const keys = axisKeys(axis)}
					{#if axis.kind === RAMP}
						{@const current = rampValues(axis, theme)}
						<fieldset>
							<legend>{axis.label}</legend>
							{#each [['h1', 'h1', axis.h1], ['h6', 'h6', axis.h6], ['power', 'Scale', axis.power]] as [part, label, range] (part)}
								<label class="slider">
									<span>{label}</span>
									<input
										type="range"
										min={range.min}
										max={range.max}
										step={range.step}
										value={current[part]}
										oninput={(event) => setTheme(keys[part], Number(event.currentTarget.value))}
									/>
									<output>{current[part]}{axis.unit}</output>
								</label>
							{/each}
						</fieldset>
					{:else if axis.kind === CHOICE}
						{@const current = fixedValue(axis, theme)}
						<label class="field">
							<span>{axis.label}</span>
							<select
								value={String(current)}
								onchange={(event) => setTheme(keys.value, axis.options.find((option) => String(option.value) === event.currentTarget.value)?.label)}
							>
								{#each axis.options as option (option.value)}
									<option value={String(option.value)}>{option.label}</option>
								{/each}
							</select>
						</label>
					{:else if axis.kind === FLAG}
						<label class="field check">
							<span>{axis.label}</span>
							<input
								type="checkbox"
								checked={fixedValue(axis, theme) === 1}
								onchange={(event) => setTheme(keys.value, event.currentTarget.checked)}
							/>
						</label>
					{/if}
				{/each}
			{/if}
		</section>
	{/if}

	{#if error}
		<p class="error">{error}</p>
	{/if}

	<footer>
		<button class="save" onclick={save} disabled={saving || loading}>
			{saving ? 'Saving…' : 'Save'}
		</button>
	</footer>
</aside>

<style>
	/* Full height down the left edge. No backdrop and nothing fixed over
	   the page: the site stays usable while you edit, which is what makes
	   the live preview worth having. The page is not pushed aside either -
	   that would mean writing to the host document's own layout. */
	.settings-drawer {
		/* Physical, not logical: the drawer is injected into someone
		   else's document and would flip to the right edge on an RTL
		   page, which is not what "left" means here. */
		position: fixed;
		top: 0;
		bottom: 0;
		left: 0;
		z-index: 70;
		box-sizing: border-box;
		display: flex;
		flex-direction: column;
		width: min(340px, 100vw);
		padding: 16px;
		overflow-y: auto;
		overscroll-behavior: contain;
		color: var(--foreground, #111);
		background: var(--background, #fff);
		border-right: 1px solid oklch(from var(--foreground, #111) l c h / 0.12);
		box-shadow: 0 0 24px oklch(0% 0 0 / 0.12);
		font-size: 0.8125rem;
		line-height: 1.4;
	}

	header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
		margin-bottom: 4px;
	}

	h2 {
		margin: 0;
		font-size: 1rem;
		font-weight: 600;
		letter-spacing: 0;
	}

	h3 {
		margin: 0 0 8px;
		font-size: 0.6875rem;
		font-weight: 600;
		letter-spacing: 0.08em;
		text-transform: uppercase;
		color: oklch(from var(--foreground, #111) l c h / 0.55);
	}

	section {
		padding-block: 14px;
		border-top: 1px solid oklch(from var(--foreground, #111) l c h / 0.1);
	}

	.close {
		flex: none;
		width: 28px;
		height: 28px;
		padding: 0;
		border: none;
		border-radius: 50%;
		background: transparent;
		color: inherit;
		font-size: 0.75rem;
		cursor: pointer;
	}

	@media (hover: hover) {
		.close:hover {
			background: oklch(from var(--foreground, #111) l c h / 0.06);
		}
	}

	.note {
		margin: 0 0 10px;
		color: oklch(from var(--foreground, #111) l c h / 0.6);
	}

	.error {
		margin: 10px 0 0;
		color: oklch(0.55 0.2 25);
	}

	.field {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
		margin-bottom: 8px;
	}

	.field > span {
		flex: none;
		width: 5.5rem;
		color: oklch(from var(--foreground, #111) l c h / 0.6);
	}

	.field.check {
		justify-content: flex-start;
	}

	input[type='text'],
	select {
		flex: 1;
		min-width: 0;
		box-sizing: border-box;
		height: 30px;
		padding: 0 6px;
		color: inherit;
		background: transparent;
		border: 1px solid oklch(from var(--foreground, #111) l c h / 0.2);
		border-radius: 8px;
		font: inherit;
	}

	input[type='text']:focus-visible,
	select:focus-visible {
		outline: none;
		border-color: var(--editing, #2563eb);
		box-shadow: inset 0 0 0 1px var(--editing, #2563eb);
	}

	/* The swatch and its hex edit the same value; the swatch is for
	   choosing, the field is for pasting one you already have. */
	.field.color input[type='color'] {
		flex: none;
		width: 34px;
		height: 30px;
		padding: 2px;
		background: transparent;
		border: 1px solid oklch(from var(--foreground, #111) l c h / 0.2);
		border-radius: 8px;
		cursor: pointer;
	}

	.hex {
		font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
		text-transform: lowercase;
	}

	fieldset {
		margin: 0 0 10px;
		padding: 8px 10px;
		border: 1px solid oklch(from var(--foreground, #111) l c h / 0.12);
		border-radius: 10px;
	}

	legend {
		padding: 0 4px;
		font-weight: 600;
	}

	.slider {
		display: grid;
		grid-template-columns: 2.25rem 1fr 3.25rem;
		align-items: center;
		gap: 6px;
	}

	.slider span {
		color: oklch(from var(--foreground, #111) l c h / 0.6);
	}

	.slider input {
		width: 100%;
		min-width: 0;
	}

	output {
		font-variant-numeric: tabular-nums;
		text-align: right;
		color: oklch(from var(--foreground, #111) l c h / 0.6);
	}

	/* Sticks to the bottom of the drawer, above the scrolling content. */
	footer {
		position: sticky;
		bottom: 0;
		display: flex;
		justify-content: flex-end;
		margin-top: auto;
		padding-top: 12px;
		padding-bottom: 4px;
		background: var(--background, #fff);
	}

	.save {
		height: 32px;
		padding: 0 1rem;
		border: none;
		border-radius: 9999px;
		background: var(--editing, #2563eb);
		color: var(--background, #fff);
		font-size: 0.8125rem;
		font-weight: 600;
		cursor: pointer;
	}

	.save:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
</style>
