contact_links:
  - name: Vowel on Twitter
    url: https://twitter.com/tryvowel
    about: Get in touch with questions or ideas.
  - name: Sam on Twitter
    url: https://twitter.com/samlfair
    about: Get in touch to chat.
